### ISSUE TITLE
Nothing is displayed when running the script

### ISSUE THREAD

**Issue by sbm1990** [AJ-TechSoul/ELECTRON-4-PHP#1]
Hello AJ-Tech i have followed all the steps recommended in these but when i run the script it displayed nothing

**Comment by AJ-TechSoul** [comment]
Which OS you are using ?

**Comment by sbm1990** [comment]
windows

**Comment by AJ-TechSoul** [comment]
Hi @sbm1990  I have updated in my docs that for now it will only run on mac without php installation. but for linux and windows you need to first install php and then it will work. Need people to contribute on windows and linux platform

**Comment by sbm1990** [comment]
Thanks for the reply it will be great if  u provide on how to start it on windows platform

**Comment by AJ-TechSoul** [comment]
Even i want to make a window platform working. Because right now i am using PHPDesktop for Window platform. 
If however i can install php in windows then my code will work in there.

**Comment by AJ-TechSoul** [comment]
I was working on putting this feature in windows, and guess what...
its working...  :laughing:  now i am making a package in npm so that you could use php 7.2.2 (latest)
![successphpworking](https://user-images.githubusercontent.com/27248672/36411395-73fcceee-163b-11e8-895a-90153f896496.png)
Give me some time for add feature officially.

**Comment by sbm1990** [comment]
I am eagerly waiting for this feature

**Comment by AJ-TechSoul** [comment]
https://github.com/AJ-TechSoul/ELECTRON-4-PHP
updated for windows also. Please use and  check it.  Soon i am going to write a proper code to support Linux, Mac and Windows all together at once. 
This is a temporary fix just for you brother. :)

**Comment by sbm1990** [comment]
Hello AJTech Thanks for this quick response .I have used latest code but the results are same it is still showing blank page.....

**Comment by AJ-TechSoul** [comment]
Try to Restart your cmd

**Comment by doublevie** [comment]
Nothing is displayed in packaged app
php wont start

**Comment by AJ-TechSoul** [comment]
while uploading Github didnt uploaded the www folder so this issue is coming. I am uploading it now please see it

**Comment by AJ-TechSoul** [comment]
@doublevie  which OS you are in

**Comment by doublevie** [comment]
found it , i must have php added in environment variables , it work now without do that  with this code
const server = new PHPServer({
    php: "php/php.exe",
});
