### ISSUE TITLE
Issue with this existing

### ISSUE THREAD

**Issue by lordraz0r** [AJ-TechSoul/ELECTRON-4-PHP#10]
So what possible use case on this earth would require this and do you realize the performance bottleneck doing this would cause?  Electron is a wrapper for javascript applications to run as desktop applications... NOT A THING YOU SHOULD BUTCHER PHP INTO!!!

**Comment by AJ-TechSoul** [comment]
See this was made to make life easier for php developers. People can't change their whole php code into JS just to for electron. This is just there as an Option. If you don't Like then please don't use it. For you there is Electron. This for people who were searching for an option and i provided them.  This is just for Solution for now, for performance, we will see later. As per now, Performance is also not an issue as it works with PHP 7.2
Thanks.

**Comment by lordraz0r** [comment]
No this is not closed! "Performance is also not an issue as it works with PHP 7.2" is completely false! You are still basically running an entire instance of a PHP server for zero reason. Using Electron in this way is like using a screwdriver to smash a nail into the wall. Also I know of no competent PHP developers that can't code Javascript.

**Comment by juppwerner** [comment]
AJ-TechSoul and userabuser, I totally agree with both of you.

Thanks a lot for this interesting repository!

Regards
Joachim

**Comment by shahidmau** [comment]
I congratulate and thanks for this awesome library. There are several reasons to have this.

- Wordpress, drupal, yii, laravel, joomla and **thousands** of awesome php libraries/frameworks are there which could be easily ported to the desktop app (including power of the Nodejs).
- We can re-write and can do everything in Nodejs but is it worth to **re-invent** all those popular solutions available in the market just for the sake of some **performance** benefit?
- I have a **very big** project (coded in **years** in Php) which I ported to the desktop app in few days. My client (**paying** client) is **happy** with the performance so I am.
- We can create a good project in a few days (using Yii) which others can't do in months in Nodejs.
- And last, why we are afraid of experiment new things? 

Thanks again **AJ AJ-TechSoul** keep working on this.
