### ISSUE TITLE
add new php extension

### ISSUE THREAD

**Issue by alirmohammadi** [AJ-TechSoul/ELECTRON-4-PHP#11]
I want to use source guardian to encrypt my source code of the project and I need to add a special extension, I add this to php.ini and copy extension to ext folder but it doesn't work 
in the tutorial of source guardian we need to change php.ini of apache but here I can't find any way to add and run this extension for ELECTORN4PHP

**Comment by AJ-TechSoul** [comment]
Try changing the PHP.ini of electron4php. Which is in PHP folder.
