### ISSUE TITLE
Error when start

### ISSUE THREAD

**Issue by Kenjy62** [AJ-TechSoul/ELECTRON-4-PHP#13]
PHP Server error { Error: spawn php ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn php',
  path: 'php',
  spawnargs:
   [ '-S',
     '127.0.0.1:80',
     '-d',
     'display_errors=1',
     '-d',
     'expose_php=0' ] }
PHP Server closed

Directory permission checked and UAC is off..

**Comment by AJ-TechSoul** [comment]
Which Operating System you are using?
Please run setenv.bat



*AJ Kumar*

*(Founder & CEO)*

*Mobile : +91 9862542983*

*Email : techsoul4@gmail.com <techsoul4@gmail.com>Website : www.techsoul.in
<http://www.techsoul.in/>*

**Comment by Kenjy62** [comment]
i use Windows 10.
I launch setenv.bat and same problems: /

**Comment by AJ-TechSoul** [comment]
Run setenv.bat with Administrator Access. (Run as Administrator)
In windows 8 and above they treat all these bat files as virus by default.


*AJ Kumar*

*(Founder & CEO)*

*Mobile : +91 9862542983*

*Email : techsoul4@gmail.com <techsoul4@gmail.com>Website : www.techsoul.in
<http://www.techsoul.in/>*
