### ISSUE TITLE
Packaging Error

### ISSUE THREAD

**Issue by HimasRafeek** [AJ-TechSoul/ELECTRON-4-PHP#16]
When trying to package the app using 
`npm run package-win` 

It throws an error in the console

`CANNOT RUN WITH NODE 10.16.3
Electron Packager requires Node 4.0 or above.`

**Comment by AJ-TechSoul** [comment]
Please go through this link.
https://github.com/electron/electron-packager/issues/863
this issue is from main electron.


*AJ Kumar*

*(Founder & CEO)*

*Mobile : +91 9862542983*

*Email : techsoul4@gmail.com <techsoul4@gmail.com>Website : www.techsoul.in
<http://www.techsoul.in/>*
