### ISSUE TITLE
Please write a guide on how to do this on windows

### ISSUE THREAD

**Issue by mahmed0715** [AJ-TechSoul/ELECTRON-4-PHP#17]
Please write a guide how to get this work on windows. Tia

**Comment by AJ-TechSoul** [comment]
Okay sure i will make a video or picture guide on this.


*AJ Kumar*

*(Founder & CEO)*

*Mobile : +91 9862542983*

*Email : techsoul4@gmail.com <techsoul4@gmail.com>Website : www.techsoul.in
<http://www.techsoul.in/>*

**Comment by Gshira1211** [comment]
hello I need help in the configuration on windows OS I install dependencies and start it but nothing happens
![Capturenpm](https://user-images.githubusercontent.com/41670129/64954828-f9d1bc00-d886-11e9-961c-92f9fcadedf1.JPG)

**Comment by AJ-TechSoul** [comment]
Are you using the Windows Version of Electron-4-PHP ?
if yes then it should working fine. I think there is problem in
installation. Please use this method.

# Clone this repository
git clone https://github.com/AJ-TechSoul/ELECTRON-4-PHP# Go into the
repositorycd ELECTRON-4-PHP# Install dependencies*npm install*# Run
the app*npm start*



*AJ Kumar*

*(Founder & CEO)*

*Mobile : +91 9862542983*

*Email : techsoul4@gmail.com <techsoul4@gmail.com>Website : www.techsoul.in
<http://www.techsoul.in/>*

**Comment by AJ-TechSoul** [comment]
Are you using the Windows Version of Electron-4-PHP ?
if yes then it should working fine. I think there is problem in
installation. Please use this method.

# Clone this repository
git clone https://github.com/AJ-TechSoul/ELECTRON-4-PHP
# Go into the repository
cd ELECTRON-4-PHP
# Install dependencies
npm install
# Run the app
npm start

**Comment by AJ-TechSoul** [comment]
If you are using windows branch then please try using master.
https://github.com/AJ-TechSoul/ELECTRON-4-PHP/tree/master

**Comment by Gshira1211** [comment]
this want I get after cloning, installing and run the master one on windows OS 
![2019-09-17](https://user-images.githubusercontent.com/41670129/65043124-987b1d00-d95a-11e9-8ee7-c79e51e5f4f7.png)


> If you are using windows branch then please try using master.
> https://github.com/AJ-TechSoul/ELECTRON-4-PHP/tree/master
> and Please make sure you
> use **npm install** command before **npm start**
> I tried again now and it works.

**Comment by AJ-TechSoul** [comment]
Please run setenv.bat file in the project folder. Then again run using npm
start.


*AJ Kumar*

*(Founder & CEO)*

*Mobile : +91 9862542983*

*Email : techsoul4@gmail.com <techsoul4@gmail.com>Website : www.techsoul.in
<http://www.techsoul.in/>*

**Comment by Gshira1211** [comment]
thx it works now I have added 
` php: "php\\php.exe",` in line 66 on the  main.js for the ELECTRON-4-PHP-master

**Comment by AJ-TechSoul** [comment]
That's Great News.


*AJ Kumar*

*(Founder & CEO)*

*Mobile : +91 9862542983*

*Email : techsoul4@gmail.com <techsoul4@gmail.com>Website : www.techsoul.in
<http://www.techsoul.in/>*
