### ISSUE TITLE
open folder

### ISSUE THREAD

**Issue by kev0629** [AJ-TechSoul/ELECTRON-4-PHP#18]
hello, I want to know if it's normal that when I use "npm start" it open the app and also the folder where there is the php file ?

**Comment by AJ-TechSoul** [comment]
Yes for first time its normal because the .bat file is needs to run in
order to get php run in electron.


*AJ Kumar*

*(Founder & CEO)*

*Mobile : +91 9862542983*

*Email : techsoul4@gmail.com <techsoul4@gmail.com>Website : www.techsoul.in
<http://www.techsoul.in/>*

**Comment by TheDucky** [comment]
Is there a way to disable or hide it?
It's quite annoying that it keeps opening the directory after starting the Electron App.

**Comment by AJ-TechSoul** [comment]
Yeah its possible in main.js you need to 
comment line number 18 in main.js
because in line number 134 its already mention.
i had kept that for testing purpose btw.
