### ISSUE TITLE
Php doesnt work!

### ISSUE THREAD

**Issue by MEGAMINDMK** [AJ-TechSoul/ELECTRON-4-PHP#19]
Well i tried alot on you php electron just dont want to get started
So I have a better version here https://github.com/MEGAMINDMK/PHP-Electronjs

**Comment by AJ-TechSoul** [comment]
I will check.

**Comment by AJ-TechSoul** [comment]
@MEGAMINDMK  , i saw it and tried to run in fresh-windows, but found that  says php not found, and i thought of putting that in your issue section but then i thought to leave it. i think you can work more better.
