### ISSUE TITLE
Building Application

### ISSUE THREAD

**Issue by successful-fella** [AJ-TechSoul/ELECTRON-4-PHP#24]
Hello,

Such a nice initiative, I really like the idea!

I used [electron-builder](https://github.com/electron-userland/electron-builder) to pack the electron app. From CLI it was working, but after packing, it just shows blank white screen. Following are the steps to reproduce the problem -

- Create src folder and put a PHP project in it.
- Modify main.js file and append "src/" in loadURL (line 88)
- Test using npm start
- Now pack app using electron-builder
- Run .exe file

I think I'm doing something wrong or is it just that electron-builder won't pack this properly? As for you, what do you use to pack the application?

**Comment by successful-fella** [comment]
Wanted to add that it shows blank without changing main.js and adding src folder too. Using CLI it shows php version page as expected though.

**Comment by brandsafric** [comment]
Hi Successful-Fella, please how did you solve the issue, were you able to successfull bundle a working php application.

**Comment by successful-fella** [comment]
@brandsafric Ah sorry. I bundled it by running `npm run package-win` which ran electron-packager (see package.json file). Previously it didn't properly pack and the reason was unclear. That's why I closed the issue without describing.
