### ISSUE TITLE
PHP server not started. Retrying...

### ISSUE THREAD

**Issue by PeaKyyI** [AJ-TechSoul/ELECTRON-4-PHP#27]
I have the same error than sheerazahmadpk, the console display PHP server not started. Retrying...
I need help 
thanks.

**Comment by PeaKyyI** [comment]
Ive got the answer like Rajeshwaran2001 said you nedd to replace the server creation code in MAIN.js by this :
const server = new PHPServer({
  php: "php/php.exe", // <==== ADDED
  port: 5555,
  directory: __dirname,
  directives: {
  display_errors: 1,
  expose_php: 1
  }
  });

dont forget to keep this line 
const PHPServer = require('php-server-manager');
if is display 'PHPServer not define'
I hope it will help

**Comment by AJ-TechSoul** [comment]
Thanks its really good


*AJ Kumar*

*(Founder & CEO)*

*Mobile : +91 9862542983*

*Email : techsoul4@gmail.com <techsoul4@gmail.com>Website : www.techsoul.in
<http://www.techsoul.in/>*
