### ISSUE TITLE
laravel 8 can't run using this, because laravel only runs on php version 7.4

### ISSUE THREAD

**Issue by nazrul-dev** [aj-techsoul/ELECTRON-4-PHP#38]
laravel 8 can't run using this, because laravel only runs on php version 7.4 and above, can you develop with different php version releases

**Comment by winnie80** [comment]
what if you upgrade your local php to version 8? cause electron will use local php

**Comment by aj-techsoul** [comment]
Its upgraded to php 8.2 now.
