### ISSUE TITLE
NFC Access

### ISSUE THREAD

**Issue by emresaracoglu** [aj-techsoul/ELECTRON-4-PHP#42]
H,

This repo has been very useful to my project, thank you. I am trying to develop an application.  The PHP application I'm trying to develop needs to use NFC card reading and writing. Can I access NFC card reading and writing with PHP?

**Comment by aj-techsoul** [comment]
Hi @emresaracoglu Thanks that you find this project usefull.
Regarding the NFC this is possible only when you make a api script in c++ or python, and then call that with parameters with php exec command. 
Hope that helps.

**Comment by emresaracoglu** [comment]
@aj-techsoul Thank you for your answer.
