### ISSUE TITLE
PHP version update

### ISSUE THREAD

**Issue by Andre-Rodrigues-Dev-Web** [aj-techsoul/ELECTRON-4-PHP#43]
Weeks ago I was looking at the project, and I noticed that it was in PHP version 7.0. I cloned the repository and updated it to PHP 8.1, if you want I can upload the update I made, but you will need access as a project contributor to make the pull requests.

**Comment by aj-techsoul** [comment]
Thanks Andre, i am making you as a contributor. Appreciated Bro.
