### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by PKhaled** [AJ-TechSoul/ELECTRON-4-PHP#7]
Hello ..
When write " npm start " into project folder this error appears " PHP server not started. Retrying... ".
Thanks

**Comment by PKhaled** [comment]
Solved
but all these files to run a small app!!!
and the source code is require!
or I did something wrong?
![a](https://user-images.githubusercontent.com/42207697/43840180-5043a1ac-9b20-11e8-9b6f-d0f3c4e3b863.png)

**Comment by AJ-TechSoul** [comment]
You did right actually you need these files to run in Windows.



*AJ Kumar*

*(Founder & CEO)*

*Mobile : +91 9862542983*

*Email : techsoul4@gmail.com <techsoul4@gmail.com>Website : www.techsoul.in
<http://www.techsoul.in/>*

**Comment by PKhaled** [comment]
Ok, Thanks

**Comment by AJ-TechSoul** [comment]
I think this solution is enough, if it works nicely  then please do let me know about it so that i could close this as issue.
