### ISSUE TITLE
2 windows open

### ISSUE THREAD

**Issue by andrestc18** [AJ-TechSoul/ELECTRON-4-PHP#9]
Hello, first I congratulate you for that excellent plug-in for electron, I wanted to ask you every time I generated the npm start or I generated the app with electron packager and I open the program two windows exit exactly the same with my program.
In the cmd there are two server runs, it's like if you hit it twice, which I do not do.

**Comment by AJ-TechSoul** [comment]
No for first time it hits twice because first time it enables or sets  PHP
Environment. And 2nd time it restarts so that you can use PHP in a great
way inside electron.

**Comment by AJ-TechSoul** [comment]
Hey,

I just signed the petition "Manohar Lal Khattar and Sunil Bharti Mittal:
Restore 52-acres of felled forest. Keep real-estate out of the entire
Aravalli zone." and wanted to see if you could help by adding your name.

Our goal is to reach 101,376 signatures and we need more support. You can
read more and sign the petition here:

https://chn.ge/2QE8GeF

Thanks!
Ajay

**Comment by juppwerner** [comment]
Hi,

can it be that this is due to two places where `app.on('ready', createWindow)` appears in the provided `main.js`?

I removed the second line (arround line 116) and now thereis only one window.

Regards
Joachim

**Comment by AJ-TechSoul** [comment]
Yes, you are right but one window should open for setting up PHP Environment which is setenv.bat in windows.

**Comment by AJ-TechSoul** [comment]
I have did the changes you said, now only one window coming. so now i am closing
